### PR TITLE
Register u to excel redo

### PR DESCRIPTION
**Pull request by Eiriksb**
Added so admin can get a list of Users added to the database in a .xlxs format

Dialog added to ask if you want to export the list or not

### CODE REVIEW

**Review by Trivinyx — APPROVED** [review]
ser bra ut nå

**Review by GlennJoakimB — DISMISSED** [review]
Ser bra ut det ja.

**Review by Trivinyx — APPROVED** [review]
Looks nice.

**Review by GlennJoakimB — APPROVED** [review]
Ser bra ut det

**Pull request merged**
