### PR TITLE
test commit

### PR DESCRIPTION
**Pull request by Trivinyx**

### CODE REVIEW

**Review by Eiriksb — APPROVED** [review]
good

**Comment by Trivinyx** [comment]
Pipeline check and tests now work properly with the unit tests

**Review by GlennJoakimB — APPROVED** [review]
Endelig grønn!

**Comment by Trivinyx** [comment]
image

**Review by Eiriksb — APPROVED** [review]
good

**Review by sebmid — APPROVED** [review]
done and dusted

**Pull request merged**
